[tools]
wasm_bindgen = "0.2.85"

[build]
filehash = false
pattern_script = "<script type=\"module\">import init, { koboldCallback } from '{base}{js}';init('{base}{wasm}');window.koboldCallback = koboldCallback;</script>"
