[package]
name = "kobold_todomvc_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kobold = { path = "../../crates/kobold", features = [] }
gloo-storage = "0.2.1"
wasm-bindgen = "0.2.84"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "HtmlInputElement",
]
