[tools]
wasm_bindgen = "0.2.84"

[build]
filehash = false
pattern_script = "<script type=\"module\">import init, { __kobold_event_handler } from '{base}{js}';init('{base}{wasm}');window.__kobold_event_handler = __kobold_event_handler;</script>"

# Does not work with `trunk serve`
# public_url = "./"
