[workspace]
members = [
    "crates/kobold",
    "crates/kobold_macros",
    "examples/clicker",
]

[patch.crates-io]
kobold_macros = { path = "crates/kobold_macros" }

[profile.release]
lto = true

[profile.bench]
lto = "fat"
codegen-units = 1