[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[profile.dev]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.bench]
lto = "fat"
codegen-units = 1
