[package]
name = "kobold_router"
version = "0.1.0"
authors = ["Bailey Townsend"]
edition = "2024"
license = "MPL-2.0"
readme = "../../README.md"
keywords = ["web", "wasm", "router", "kobold"]
categories = ["wasm", "web-programming"]
description = "A router for web applications written with Kobold"
repository = "https://github.com/maciejhirsz/kobold"
documentation = "https://docs.rs/kobold"

[dependencies]
kobold = { path = "../kobold" }
matchit = "0.8.0"
wasm-bindgen.workspace = true

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Location", "History"]
