[package]
name = "tests"
version = "0.1.0"
edition = "2018"

[dependencies]
kobold = { path = "../../crates/kobold" }
wasm-bindgen = "0.2.74"
console_error_panic_hook = "0.1"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
