[package]
name = "kobold_csv_editor_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
compact_str = "0.9.0"
gloo-console = "0.3.0"
kobold = { path = "../../crates/kobold" }
logos = "0.12.1"
wasm-bindgen-futures.workspace = true

[dependencies.web-sys]
version = "0.3"
features = ["console", "HtmlInputElement", "File", "FileList"]
