[package]
name = "router"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
kobold = { path = "../../crates/kobold" }
# kobold_router = { path = "../../crates/kobold_router" }
wasm-bindgen.workspace = true

[dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "HtmlInputElement",
    "console",
    "Window",
    "Location",
    "History",
]
