[tools]
wasm_bindgen = "0.2.84"

[build]
filehash = false
pattern_script = "<script type=\"module\">import init from '{base}{js}';init('{base}{wasm}').then(wasm=>window.wasm=wasm);</script>"

# Does not work with `trunk serve`
# public_url = "./"
