name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  checkfmt:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/base-setup
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          toolchain: ${{ matrix.rust }}
      - name: Check in package npm_lib
        working-directory: ./examples/npm_lib
        run: |
          # Install Yarn for Node.js
          export PATH="/usr/bin:$PATH"  # Ensure system binaries are in PATH
          sudo yarn
          sudo yarn run esbuild
          cargo install --locked trunk
          RUST_LOG=debug trunk --config ./ build
          # Note: The `--vers "0.2.100"` must match the version of
          # `wasm-bindgen` in Cargo.toml file
          cargo install wasm-bindgen-cli --vers "0.2.100"
          cargo +nightly build --package kobold_npm_lib_example \
            --bin main --target wasm32-unknown-unknown -Zdoctest-xcompile --verbose
          cargo check
          cargo fmt --check
      - name: Check in parent
        working-directory: ./
        shell: bash
        run: |
          cargo check --features serde,stateful --workspace --all-targets --bins --examples
          cargo fmt --check

  miri:
    # needs: [checkfmt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/base-setup
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          toolchain: nightly
      - name: Install Miri
        working-directory: ./
        shell: bash
        run: |
          # Source the retry script
          source ./.github/actions/retry-script/retry.sh
          MIRI_NIGHTLY=nightly-$(retry 10 curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)

          echo "Installing latest nightly with Miri: $MIRI_NIGHTLY"
          rustup set profile minimal
          rustup default "$MIRI_NIGHTLY"
          rustup component add miri
          cargo miri setup
      - name: Run Miri tests
        working-directory: ./crates/kobold
        shell: bash
        run: |
          MIRIFLAGS='-Zmiri-strict-provenance' cargo miri test

  tests:
    # needs: [checkfmt, miri]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/base-setup
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          toolchain: nightly
      - name: Test in package npm_lib
        working-directory: ./examples/npm_lib
        shell: bash
        run: |
          # Source retry script
          source ../../.github/actions/retry-script/retry.sh

          # Install wasm-bindgen-cli with retries
          # Note: The `--vers "0.2.100"` must match the version of `wasm-bindgen` in Cargo.toml file
          retry 10 cargo install wasm-bindgen-cli --vers "0.2.100"

          # Install Yarn for Node.js
          export PATH="/usr/bin:$PATH"  # Ensure system binaries are in PATH
          sudo yarn
          sudo mkdir -p output  # Ensure output directory exists
          sudo yarn run esbuild

          # Install trunk with retries
          retry 10 cargo install --locked trunk

          RUST_LOG=debug trunk --config ./ build

          # Run wasm tests specifically
          wasm-pack test --node
